/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import logic.controller.Controller;
import view.interfaces.viewInterface;

/**
 *
 * @author pedro
 */
public class MainPanel extends javax.swing.JFrame implements viewInterface {

    Controller controller;
    /**
     * Creates new form MainPanel1
     */
    public MainPanel(Controller pController) {
        initComponents();
        controller=pController;
        controller.setMainPanel(this);
        addEvents();
    }
    
    public MainPanel(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        scrollAdminTickets = new javax.swing.JScrollPane();
        listAdminTickets = new javax.swing.JList<>();
        scrollTicketsSinAtender = new javax.swing.JScrollPane();
        listTicketsSinAtender = new javax.swing.JList<>();
        cmbboxAtendientes = new javax.swing.JComboBox<>();
        cmbboxEstados = new javax.swing.JComboBox<>();
        btnEstado = new javax.swing.JButton();
        btnEstadisticas1 = new javax.swing.JButton();
        btnEstadisticas2 = new javax.swing.JButton();
        btnEstadisticas3 = new javax.swing.JButton();
        btnAtender = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnCambiarAtendiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listAdminTickets.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollAdminTickets.setViewportView(listAdminTickets);

        listTicketsSinAtender.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollTicketsSinAtender.setViewportView(listTicketsSinAtender);

        cmbboxAtendientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbboxEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnEstado.setText("Clasificar");

        btnEstadisticas1.setText("Estadística 1");

        btnEstadisticas2.setText("Estadística 2");

        btnEstadisticas3.setText("Estadística 3");

        btnAtender.setText("Atender");

        btnFinalizar.setText("Finalizar");

        btnCambiarAtendiente.setText("Cambiar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbboxEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollAdminTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEstadisticas1)
                    .addComponent(btnEstadisticas2)
                    .addComponent(btnEstadisticas3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(scrollTicketsSinAtender, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbboxAtendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCambiarAtendiente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAtender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbboxAtendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarAtendiente))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollTicketsSinAtender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollAdminTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnEstadisticas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEstadisticas2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEstadisticas3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbboxEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstado)
                    .addComponent(btnAtender)
                    .addComponent(btnFinalizar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnCambiarAtendiente;
    private javax.swing.JButton btnEstadisticas1;
    private javax.swing.JButton btnEstadisticas2;
    private javax.swing.JButton btnEstadisticas3;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JComboBox<String> cmbboxAtendientes;
    private javax.swing.JComboBox<String> cmbboxEstados;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JList<String> listAdminTickets;
    private javax.swing.JList<String> listTicketsSinAtender;
    private javax.swing.JScrollPane scrollAdminTickets;
    private javax.swing.JScrollPane scrollTicketsSinAtender;
    // End of variables declaration//GEN-END:variables
    
    
    public void setVisibleMainPanel(boolean pVisibility){
        this.setVisible(pVisibility);
    }
    
    public JButton getBtnAtender(){
        return btnAtender;
    }
    
    public JButton getBtnCambiarAtendiente(){
        return btnCambiarAtendiente;
    }
    
    public JButton getBtnEstadisticas1(){
        return btnEstadisticas1;
    }
    
    public JButton getBtnEstadisticas2(){
        return btnEstadisticas2;
    }
    
    public JButton getBtnEstadisticas3(){
        return btnEstadisticas3;
    }
    
    public JButton getBtnEstado(){
        return btnEstado;
    }
    
    public JButton getBtnFinalizar(){
        return btnFinalizar;
    }
    
    public JComboBox getCmbboxAtendientes(){
        return cmbboxAtendientes;
    }
    
    public JComboBox getCmbboxEstados(){
        return cmbboxEstados;
    }
    
    public JList<String> getListAdminTickets(){
        return listAdminTickets;
    }
    
    public JList<String> getListTicketsSinAtender(){
        return listTicketsSinAtender;
    }
    
    private void addEvents(){
        this.btnAtender.addActionListener(controller);
        this.btnCambiarAtendiente.addActionListener(controller);
        this.btnEstadisticas1.addActionListener(controller);
        this.btnEstadisticas2.addActionListener(controller);
        this.btnEstadisticas3.addActionListener(controller);
        this.btnEstado.addActionListener(controller);
        this.btnFinalizar.addActionListener(controller);
        this.cmbboxAtendientes.addActionListener(controller);
        this.cmbboxEstados.addActionListener(controller);
        this.listAdminTickets.addListSelectionListener(controller);
        this.listTicketsSinAtender.addListSelectionListener(controller);
    }

    @Override
    public void setVisibleTicketGenerator(boolean pVisibility) {
        
    }
}